server:
  port: 8082
  mode: "dev"
mysql:
  host: mysql
  port: 3306
  username: root
  password: 123456
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 300
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.001.log"
  maxSize:    500                     
  maxBackups: 3
  maxAge:     28
  compress:   true
redis:
  host: redis
  port: 6379
  password:
  database: 0
