server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: abc13579
  dbname: shopdev
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 300
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.001.log"
  maxSize:    500                     
  maxBackups: 3
  maxAge:     28
  compress:   true
